[project]
name = "codigos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ib-async>=2.1.0",
    "jupyter>=1.1.1",
    "kagglehub>=1.0.0",
    "pandas>=3.0.0",
    "tws>=0.0.1",
    "yfinance>=1.1.0",
]
